import 'dart:io';

import 'package:flutter_app_icons_generator/src/flavors/flavor_model.dart';
import 'package:flutter_app_icons_generator/src/shared/xcode/swift_version_resolver.dart';

/// Generates per-flavor `.xcconfig` files in the iOS Flutter directory.
///
/// Each flavor gets three xcconfig files (Debug, Release, Profile) that
/// `#include` the base Flutter xcconfigs and add flavor-specific overrides
/// for `PRODUCT_BUNDLE_IDENTIFIER`, `ASSETCATALOG_COMPILER_APPICON_NAME`,
/// and the project's existing Swift language version.
class IosXcconfigGenerator {
  /// Creates xcconfig files for all flavors in `ios/Flutter/`.
  void generate(String projectRoot, Map<String, FlavorConfig> flavors) {
    final flutterDir = Directory('$projectRoot/ios/Flutter');
    if (!flutterDir.existsSync()) {
      flutterDir.createSync(recursive: true);
    }

    final swiftVersion = SwiftVersionResolver().resolveIos(projectRoot);
    final swiftVersionLine = swiftVersion == null
        ? ''
        : 'SWIFT_VERSION = $swiftVersion\n';

    for (final entry in flavors.entries) {
      final flavorName = entry.key;
      final config = entry.value;
      final iconName = 'AppIcon-$flavorName';

      File('${flutterDir.path}/Debug-$flavorName.xcconfig')
          .writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $flavorName (Debug)
#include "Debug.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
$swiftVersionLine''');

      File('${flutterDir.path}/Release-$flavorName.xcconfig')
          .writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $flavorName (Release)
#include "Release.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
$swiftVersionLine''');

      File('${flutterDir.path}/Profile-$flavorName.xcconfig')
          .writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $flavorName (Profile)
#include "Release.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
$swiftVersionLine''');
    }
  }
}
