import 'dart:io';

import 'package:flutter_app_icons_generator/src/core/platform_updater.dart';

/// Linux platform configuration updater.
///
/// Verifies that the Flutter Linux runner (typically `my_application.cc`)
/// references the generated icon file (`app_icon.png`) via
/// `gtk_window_set_icon_from_file`. If the reference is missing and the
/// runner file exists, it attempts to add the reference. If the runner
/// file is not found, or the expected pattern cannot be located, the
/// updater logs that verification was skipped (best-effort).
class LinuxUpdater implements PlatformUpdater {
  /// The icon filename generated by [LinuxIconGenerator].
  static const String _iconFileName = 'app_icon.png';

  /// Candidate runner file names in order of preference.
  static const List<String> _runnerFileNames = [
    'my_application.cc',
    'main.cc',
  ];

  @override
  Future<void> update(String projectRoot) async {
    final linuxDir = Directory('$projectRoot/linux');

    // If the linux directory does not exist, the platform is not initialized.
    if (!linuxDir.existsSync()) {
      return;
    }

    // Try to find the runner file.
    final runnerFile = _findRunnerFile(linuxDir);
    if (runnerFile != null) {
      _ensureIconReference(runnerFile);
      return;
    }

    // Alternatively, check if CMakeLists.txt exists and references the icon.
    final cmakeFile = File('${linuxDir.path}/CMakeLists.txt');
    if (cmakeFile.existsSync()) {
      _verifyCMakeReference(cmakeFile);
      return;
    }

    // Neither runner file nor CMakeLists.txt found — skip.
    stderr.writeln(
      '[Linux] Verification skipped: no runner file or CMakeLists.txt found.',
    );
  }

  /// Finds the first matching runner file in [linuxDir].
  File? _findRunnerFile(Directory linuxDir) {
    for (final name in _runnerFileNames) {
      final file = File('${linuxDir.path}/$name');
      if (file.existsSync()) {
        return file;
      }
    }
    return null;
  }

  /// Ensures the runner file contains a `gtk_window_set_icon_from_file`
  /// call referencing our icon.
  void _ensureIconReference(File runnerFile) {
    var content = runnerFile.readAsStringSync();

    // Check if the icon is already referenced.
    if (content.contains(_iconFileName)) {
      return;
    }

    // Look for an existing gtk_window_set_icon_from_file call.
    final iconFromFilePattern = RegExp(
      r'gtk_window_set_icon_from_file\s*\([^)]*\)',
    );

    if (iconFromFilePattern.hasMatch(content)) {
      // Replace the existing call's file path with our icon path.
      content = content.replaceFirst(
        iconFromFilePattern,
        'gtk_window_set_icon_from_file(GTK_WINDOW(window), "$_iconFileName", nullptr)',
      );
      runnerFile.writeAsStringSync(content);
      return;
    }

    // Look for the gtk_window_set_default_size or gtk_widget_show pattern
    // to insert our icon reference after the window is created.
    final windowShowPattern = RegExp(
      r'(gtk_window_set_default_size\s*\([^)]*\)\s*;)',
    );

    if (windowShowPattern.hasMatch(content)) {
      content = content.replaceFirst(
        windowShowPattern,
        '${windowShowPattern.firstMatch(content)!.group(0)}\n'
        '  gtk_window_set_icon_from_file(GTK_WINDOW(window), "$_iconFileName", nullptr);',
      );
      runnerFile.writeAsStringSync(content);
      return;
    }

    // Could not find a suitable insertion point — best-effort, skip.
    stderr.writeln(
      '[Linux] Verification skipped: could not locate icon insertion point '
      'in ${runnerFile.path}.',
    );
  }

  /// Verifies that `CMakeLists.txt` references the generated icon file.
  /// This is informational only — if the icon is not referenced, a message
  /// is logged but no modifications are made to the CMake file.
  void _verifyCMakeReference(File cmakeFile) {
    final content = cmakeFile.readAsStringSync();

    if (content.contains(_iconFileName)) {
      return;
    }

    // CMakeLists.txt does not reference the icon — log informational message.
    stderr.writeln(
      '[Linux] Note: CMakeLists.txt does not reference "$_iconFileName". '
      'You may need to update it manually.',
    );
  }
}
