import 'dart:io';

import 'package:flutter_app_icons_generator/src/flavors/flavor_model.dart';
import 'package:flutter_app_icons_generator/src/shared/xcode/swift_version_resolver.dart';

/// Generates per-flavor `.xcconfig` files in the macOS Flutter directory.
///
/// Each flavor gets three xcconfig files (Debug, Release, Profile) that
/// `#include` the base Flutter xcconfigs and the app-level config, then add
/// flavor-specific overrides for `PRODUCT_BUNDLE_IDENTIFIER`,
/// `ASSETCATALOG_COMPILER_APPICON_NAME`, and the project's existing Swift
/// language version.
class MacosXcconfigGenerator {
  /// Creates xcconfig files for all flavors in `macos/Flutter/`.
  void generate(String projectRoot, Map<String, FlavorConfig> flavors) {
    final flutterDir = Directory('$projectRoot/macos/Flutter');
    if (!flutterDir.existsSync()) {
      flutterDir.createSync(recursive: true);
    }

    // Detect if AppInfo.xcconfig exists (standard Flutter macOS template).
    final hasAppInfo =
        File('$projectRoot/macos/Runner/Configs/AppInfo.xcconfig').existsSync();
    final appInfoInclude =
        hasAppInfo ? '#include "../Runner/Configs/AppInfo.xcconfig"\n' : '';
    final swiftVersion = SwiftVersionResolver().resolveMacos(projectRoot);
    final swiftVersionLine =
        swiftVersion == null ? '' : 'SWIFT_VERSION = $swiftVersion\n';

    for (final entry in flavors.entries) {
      final name = entry.key;
      final config = entry.value;
      final iconName = 'AppIcon-$name';

      File('${flutterDir.path}/Debug-$name.xcconfig').writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Debug)
#include "Flutter-Debug.xcconfig"
$appInfoInclude
PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
$swiftVersionLine''');

      File('${flutterDir.path}/Release-$name.xcconfig').writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Release)
#include "Flutter-Release.xcconfig"
$appInfoInclude
PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
$swiftVersionLine''');

      File('${flutterDir.path}/Profile-$name.xcconfig').writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Profile)
#include "Flutter-Release.xcconfig"
$appInfoInclude
PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
$swiftVersionLine''');
    }
  }
}
