import 'dart:io';

import 'package:flutter_app_icons_generator/src/flavors/flavor_model.dart';

/// Generates per-flavor `.xcconfig` files in the macOS Flutter directory.
///
/// Each flavor gets three xcconfig files (Debug, Release, Profile) that
/// `#include` the base Flutter xcconfigs and add flavor-specific overrides
/// for `PRODUCT_BUNDLE_IDENTIFIER` and `ASSETCATALOG_COMPILER_APPICON_NAME`.
class MacosXcconfigGenerator {
  /// Creates xcconfig files for all flavors in `macos/Flutter/`.
  void generate(String projectRoot, Map<String, FlavorConfig> flavors) {
    final flutterDir = Directory('$projectRoot/macos/Flutter');
    if (!flutterDir.existsSync()) {
      flutterDir.createSync(recursive: true);
    }

    for (final entry in flavors.entries) {
      final name = entry.key;
      final config = entry.value;
      final iconName = 'AppIcon-$name';

      File('${flutterDir.path}/$name-Debug.xcconfig').writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Debug)
#include "Flutter-Debug.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
''');

      File('${flutterDir.path}/$name-Release.xcconfig').writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Release)
#include "Flutter-Release.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
''');

      File('${flutterDir.path}/$name-Profile.xcconfig').writeAsStringSync('''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Profile)
#include "Flutter-Release.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
''');
    }
  }
}
