import 'dart:io';

import 'package:flutter_app_icons_generator/src/core/platform_updater.dart';
import 'package:flutter_app_icons_generator/src/flavors/flavor_model.dart';

/// Updates the macOS Xcode project to reference the `AppIcon` asset catalog entry.
///
/// For non-flavor builds:
/// Ensures `ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon` is present in the
/// Xcode project build settings (`project.pbxproj`).
///
/// For flavor builds:
/// Configures per-flavor xcconfig files and Xcode schemes with the correct
/// `ASSETCATALOG_COMPILER_APPICON_NAME` and `PRODUCT_BUNDLE_IDENTIFIER`.
class MacosUpdater implements PlatformUpdater {
  /// Regex matching any `ASSETCATALOG_COMPILER_APPICON_NAME = <value>;` line.
  static final RegExp _settingPattern = RegExp(
    r'ASSETCATALOG_COMPILER_APPICON_NAME\s*=\s*[^;]+;',
  );

  @override
  Future<void> update(String projectRoot, {String? flavorName}) async {
    final pbxprojPath = '$projectRoot/macos/Runner.xcodeproj/project.pbxproj';
    final file = File(pbxprojPath);

    // If the file doesn't exist, the macOS platform may not be initialized.
    if (!file.existsSync()) {
      return;
    }

    // When running with flavors, don't modify project.pbxproj here.
    // The configureFlavors() method handles per-flavor settings via xcconfigs
    // and schemes. The pbxproj should keep the default AppIcon reference.
    if (flavorName != null) {
      return;
    }

    var content = file.readAsStringSync();

    const expectedSetting = 'ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon';

    // Check if the correct setting already exists.
    if (content.contains('$expectedSetting;')) {
      return;
    }

    // If the setting exists with a different value, replace it.
    if (_settingPattern.hasMatch(content)) {
      content = content.replaceAll(
        _settingPattern,
        '$expectedSetting;',
      );
      file.writeAsStringSync(content);
    }

    // If the setting is not present at all, Flutter project templates
    // typically include it by default, so we leave it as-is.
  }

  /// Configures macOS for all flavors at once.
  ///
  /// This method:
  /// 1. Generates xcconfig files per flavor (with PRODUCT_BUNDLE_IDENTIFIER
  ///    and ASSETCATALOG_COMPILER_APPICON_NAME).
  /// 2. Creates Xcode schemes for each flavor.
  Future<void> configureFlavors(
    String projectRoot,
    Map<String, FlavorConfig> flavors,
  ) async {
    await _generateXcconfigs(projectRoot, flavors);
    await _generateSchemes(projectRoot, flavors);
  }

  /// Generates per-flavor `.xcconfig` files in `macos/Flutter/`.
  Future<void> _generateXcconfigs(
    String projectRoot,
    Map<String, FlavorConfig> flavors,
  ) async {
    final flutterDir = Directory('$projectRoot/macos/Flutter');
    if (!flutterDir.existsSync()) {
      flutterDir.createSync(recursive: true);
    }

    for (final entry in flavors.entries) {
      final name = entry.key;
      final config = entry.value;
      final iconName = 'AppIcon-$name';

      // Debug xcconfig
      final debugContent = '''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Debug)
#include "Flutter-Debug.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
''';
      File('${flutterDir.path}/$name-Debug.xcconfig')
          .writeAsStringSync(debugContent);

      // Release xcconfig
      final releaseContent = '''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Release)
#include "Flutter-Release.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
''';
      File('${flutterDir.path}/$name-Release.xcconfig')
          .writeAsStringSync(releaseContent);

      // Profile xcconfig
      final profileContent = '''
// Generated by flutter_app_icons_generator — do not edit manually.
// Flavor: $name (Profile)
#include "Flutter-Release.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIdentifier}
ASSETCATALOG_COMPILER_APPICON_NAME = $iconName
''';
      File('${flutterDir.path}/$name-Profile.xcconfig')
          .writeAsStringSync(profileContent);
    }
  }

  /// Generates Xcode scheme files for each flavor.
  Future<void> _generateSchemes(
    String projectRoot,
    Map<String, FlavorConfig> flavors,
  ) async {
    final schemesDir = Directory(
      '$projectRoot/macos/Runner.xcodeproj/xcshareddata/xcschemes',
    );
    if (!schemesDir.existsSync()) {
      schemesDir.createSync(recursive: true);
    }

    for (final flavorName in flavors.keys) {
      final schemeContent = _buildSchemeXml(flavorName);
      final schemeFile = File('${schemesDir.path}/$flavorName.xcscheme');
      schemeFile.writeAsStringSync(schemeContent);
    }
  }

  /// Builds an Xcode scheme XML for a given flavor targeting macOS.
  String _buildSchemeXml(String flavorName) {
    return '''<?xml version="1.0" encoding="UTF-8"?>
<Scheme
   LastUpgradeVersion = "1510"
   version = "1.7">
   <BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
      <BuildActionEntries>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "YES"
            buildForArchiving = "YES"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "33CC10EC2044A3C60003C045"
               BuildableName = "Runner.app"
               BlueprintName = "Runner"
               ReferencedContainer = "container:Runner.xcodeproj">
            </BuildableReference>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <TestAction
      buildConfiguration = "Debug-$flavorName"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      shouldUseLaunchSchemeArgsEnv = "YES">
      <Testables>
      </Testables>
   </TestAction>
   <LaunchAction
      buildConfiguration = "Debug-$flavorName"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      launchStyle = "0"
      useCustomWorkingDirectory = "NO"
      ignoresPersistentStateOnLaunch = "NO"
      debugDocumentVersioning = "YES"
      debugServiceExtension = "internal"
      allowLocationSimulation = "YES">
      <BuildableProductRunnable
         runnableDebuggingMode = "0">
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "33CC10EC2044A3C60003C045"
            BuildableName = "Runner.app"
            BlueprintName = "Runner"
            ReferencedContainer = "container:Runner.xcodeproj">
         </BuildableReference>
      </BuildableProductRunnable>
   </LaunchAction>
   <ProfileAction
      buildConfiguration = "Profile-$flavorName"
      shouldUseLaunchSchemeArgsEnv = "YES"
      savedToolIdentifier = ""
      useCustomWorkingDirectory = "NO"
      debugDocumentVersioning = "YES">
      <BuildableProductRunnable
         runnableDebuggingMode = "0">
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "33CC10EC2044A3C60003C045"
            BuildableName = "Runner.app"
            BlueprintName = "Runner"
            ReferencedContainer = "container:Runner.xcodeproj">
         </BuildableReference>
      </BuildableProductRunnable>
   </ProfileAction>
   <AnalyzeAction
      buildConfiguration = "Debug-$flavorName">
   </AnalyzeAction>
   <ArchiveAction
      buildConfiguration = "Release-$flavorName"
      revealArchiveInOrganizer = "YES">
   </ArchiveAction>
</Scheme>
''';
  }
}
