import 'dart:convert';
import 'dart:io';

/// Generates a `.vscode/launch.json` file with Flutter launch configurations
/// for each app flavor.
///
/// This provides IDE support (VS Code, Cursor, etc.) so developers can
/// run/debug specific flavors directly from the editor without typing
/// CLI commands.
///
/// Each flavor gets three configurations: Debug, Profile, and Release.
/// If no flavors are configured, a single set of default configurations
/// is generated.
class LaunchJsonGenerator {
  /// Creates a [LaunchJsonGenerator].
  const LaunchJsonGenerator();

  /// Generates or updates `.vscode/launch.json` in the given [projectRoot].
  ///
  /// [flavors] is the map of flavor names (e.g., `{'dev', 'prod'}`).
  /// Each flavor is expected to have a corresponding entry point at
  /// `lib/main_<flavor>.dart`.
  ///
  /// If [flavors] is empty, generates a single default configuration
  /// using `lib/main.dart`.
  ///
  /// Returns `true` if the file was written, `false` if skipped
  /// (e.g., already exists with user modifications).
  bool generate(String projectRoot, Set<String> flavors) {
    final vscodeDir = Directory('$projectRoot/.vscode');
    if (!vscodeDir.existsSync()) {
      vscodeDir.createSync(recursive: true);
    }

    final launchFile = File('${vscodeDir.path}/launch.json');

    // If launch.json already exists, check if it was generated by us.
    // If it was modified by the user (no marker), don't overwrite.
    if (launchFile.existsSync()) {
      final existing = launchFile.readAsStringSync();
      if (!existing.contains('"author": "flutter_app_icons_generator"')) {
        return false;
      }
    }

    final configurations = <Map<String, dynamic>>[];

    if (flavors.isEmpty) {
      // No flavors — generate a simple default set.
      configurations.addAll(_buildConfigurations(
        flavorName: null,
        program: 'lib/main.dart',
      ));
    } else {
      // Generate configurations for each flavor.
      for (final flavor in flavors) {
        configurations.addAll(_buildConfigurations(
          flavorName: flavor,
          program: 'lib/main_$flavor.dart',
        ));
      }
    }

    final launchJson = {
      'version': '0.2.0',
      'metadata': {
        'author': 'flutter_app_icons_generator',
        'note': 'Auto-generated. Re-run the generator to update.',
      },
      'configurations': configurations,
    };

    // Write with standard JSON formatting.
    const encoder = JsonEncoder.withIndent('  ');
    launchFile.writeAsStringSync('${encoder.convert(launchJson)}\n');

    return true;
  }

  /// Builds Debug, Profile, and Release configurations for a flavor.
  List<Map<String, dynamic>> _buildConfigurations({
    required String? flavorName,
    required String program,
  }) {
    final modes = ['debug', 'profile', 'release'];
    final configs = <Map<String, dynamic>>[];

    for (final mode in modes) {
      final modeName = mode[0].toUpperCase() + mode.substring(1);
      final displayName = flavorName != null
          ? '$flavorName $modeName'
          : modeName;

      final config = <String, dynamic>{
        'name': displayName,
        'request': 'launch',
        'type': 'dart',
        'flutterMode': mode,
        'program': program,
      };

      if (flavorName != null) {
        config['args'] = ['--flavor', flavorName];
      }

      configs.add(config);
    }

    return configs;
  }
}
